### ISSUE TITLE
Hinzufügen von Geräten

### ISSUE THREAD

**Issue by meikelmoeller** [foxthefox/ioBroker.musiccast#10]
Geräte lassen sich nicht manuell über die IP Adresse hinzufügen. Lediglich eine Suche lässt sich ausführen. Da meine AVR in einem anderen Netzsegment ist findet der Adapter den AVR vermutlich nicht.
<img width="1296" alt="bildschirmfoto 2018-03-03 um 13 22 14" src="https://user-images.githubusercontent.com/3081176/36934186-05fff106-1ee6-11e8-87a9-4416699fc54e.png">

**Comment by foxthefox** [comment]
@meikelmoeller 
Das manuelle hinzufügen von Geräten habe ich bei der Transition zu adminV3 herausgenommen. Da zum richtigen Eintragen ohnehin die GeräteID zu ermitteln ist (noch basiert das mapping der Datenpunkte auf IP-addressen, aber die GeräteID ist unique  und stabil).
Das manuelle hinzufügen ist noch in der alten version der admin-page vorhanden.
Evtl. funktioniert folgende Vorgehensweise:
- in io_package.json des Adapters den Eintrag "materialize" auf false setzen,
- den adapter neu starten oder ggf. instanz löschen/neue instanz hinzufügen
oder
- in io_package.json des Adapters den Eintrag "materialize" löschen,
- den adapter neu starten oder ggf. instanz löschen/neue instanz hinzufügen
Damit müsste die adminv2 zum Vorschein kommen, wo es ein "+" zum manuellen Einfügen gibt.

Es ist schon anzunehmen, daß die Suchfinktion nicht in andere Netzsegmente geht. Ich benutze peer-ssdp um das Upnp Gerät zu finden.

Ob der Adapter bei richtiger IP-Adresse im anderen Segment auch richtig funktioniert, weiß ich nicht.
Falls es mit der adminv2 geklappt hat, wäre es dann ja testbar.

**Comment by meikelmoeller** [comment]
Bekomme ich leider nicht ans laufen. Ist auch nicht ganz so wichtig, vielleicht kannst du es ja bei einer kommenden Version wieder einbauen.

**Comment by foxthefox** [comment]
Habe jetzt die adminv3 identisch zu v2 umgebaut. Somit ist der manuelles anfügen wieder möglich.
Ob es dennoch mit dem anderen subnet funktioniert, müsstest du testen.
Bitte die 0.0.9 von github testen

**Comment by meikelmoeller** [comment]
Leider geht bei mir kein Fenster  auf wenn ich auf "+" oder "search" drücke. Liegt aber vermutlich an meinem ioBroker, das Teil verhält sich bei solchen Abfragen sehr strange.

**Comment by foxthefox** [comment]
Hast du den Admin Adapter in Version 3.4.4 ?
Die Funktion, auf die ich umgestellt habe, ist scheinbar erst letztens ertüchtigt worden.
Also dort bitte ggf. ein update machen, dann ist das strange evtl. auch generisch weg.
"+" soll eine neue Zeile einfügen, genau für deinen Zweck die IP des Gerätes manuell vorzugeben.

**Comment by meikelmoeller** [comment]
3.4.4 habe ich installiert, kann aber deinen Adapter dann nicht mehr installieren. Ist auch nicht ganz so wichtig, fände halt cool wenn ich per Alexa die %ualte Lautstärke einstellen könnte. Mit der Harmony App geht halt nur lauter/leiser....

**Comment by foxthefox** [comment]
sehr komisch, der adapter sollte sich installieren lassen.
Welche Fehlermeldungen kommen?
Welche node version und Betriebssystem verwendest du?

**Comment by meikelmoeller** [comment]
Moin.

Es sieht so aus dass meine ioBroker Installation durcheinander war. Nachdem
ich einige Update gemacht habe konnte ich den Musiccast Adapter
installieren und auch die IP von meinem AVR eingeben. Allerdings liefern
die angelegten Objekte keine Informationen. Möglich dass es an dem anderen
Subnetz liegt oder woran auch immer.

Wie aber schon gesagt, ist nicht wirklich wichtig für mich sondern nur ein
"nice to have".

Starting. Version 0.0.9 in /opt/iobroker/node_modules/iobroker.musiccast,
node: v6.12.3
Linux ioBroker-Pi 4.9.59-v7+

Danke dir fürs Kümmern und Pflegen.

Grüße
Michael

2018-06-08 18:10 GMT+02:00 foxthefox <notifications@github.com>:

**Comment by foxthefox** [comment]
Dann schließe ich mal den case
