### ISSUE TITLE
Name aus Einstellungen wird für Objekte nicht übernommen

### ISSUE THREAD

**Issue by Scrounger** [foxthefox/ioBroker.musiccast#11]
@foxthefox:
Den namen den ich den Einstellungen gesetzt habe, z.B. Bad
![adapter_settings](https://user-images.githubusercontent.com/6370451/38464711-9702398c-3b12-11e8-9b01-61e9da042826.jpg)

wird nicht in den Objekten übernommen, also der common.name:
![objects](https://user-images.githubusercontent.com/6370451/38464715-a60073ea-3b12-11e8-9927-069ca73c77fd.jpg)

Kannst du das bitte fixen, da ich den Namen in verschiedenen Scripten benötige, um z.B. auszugeben welches Geräte gerade noch on ist.

Danke!

**Comment by foxthefox** [comment]
Also dann packe ich den Namen noch hinten dran. Also dann ist der Name zB "MusicCast ISX-18D Küche" oder soll es anders werden? Noch ein bestimmtes Trennzeichen?

**Comment by foxthefox** [comment]
habe in 0.0.8 die Ergänzung gemacht, bitte prüfen ob es so passt.

**Comment by Scrounger** [comment]
@foxthefox 
funktioniert, danke!
