### ISSUE TITLE
Ausschalten von WX-10 über JS funktioniert nicht

### ISSUE THREAD

**Issue by jonas0806** [foxthefox/ioBroker.musiccast#15]
Hi,

das anmachen meiner WX-10 per Script funktionier einwandfrei, das ausmachen allerdings nicht. Das kuriose, über die GUI unter Objekte kann ich den status auf false setzten und es funktioniert.

Folgendes funktioniert:
`setState("musiccast.0.WX-010_047F5D13.main.power"/*Power ON/OFF(Standby)*/, 'true');`

das hier nicht:
`setState("musiccast.0.WX-010_047F5D13.main.power"/*Power ON/OFF(Standby)*/, 'false');`
habe es auch schon so probiert
`setState("musiccast.0.WX-010_047F5D13.main.power"/*Power ON/OFF(Standby)*/, 'false', true);`

Gruß Jonas

**Comment by foxthefox** [comment]
Hi Jonas,

wie sieht es mit:
setState("musiccast.0.WX-010_047F5D13.main.power", false);
aus?
Power ON/OFF(Standby) ist der Name des objects und muß glaube ich nicht mit in den Aufruf hinein.
false ohne '' sollte besser passen.

Gruß
Klaus

**Comment by jonas0806** [comment]
Hallo Klaus,

auch das funktioniert leider nicht....

Das Power ON/OFF(Standby) ist ja nur kommentiert. Ich habe es auch noch mal versucht als bool und nicht als string zu übergeben. Funktioniert allerdings alles nicht.

Gruß Jonas

**Comment by foxthefox** [comment]
Hallo Jonas,

kannst du den musiccast adapter mal in den debug modus versetzen und im log nachschauen was nach deinem setState kommt?

und probier auch einmal 

setState("musiccast.0.WX-010_047F5D13.main.power", false, false);

das 2te false steht für cmd, als true wäre es nur ein status.

Gruß
Klaus

**Comment by jonas0806** [comment]
Hallo Klaus,

danke Dir! Mit dem zweiten false klappte es.

Gruß Jonas
