### ISSUE TITLE
Changing input not working on YAS-306

### ISSUE THREAD

**Issue by MichaelDvP** [foxthefox/ioBroker.musiccast#178]
With current 1.03 the input can not be changed via adapter for YAS-306 and WX-10.  Other settings working. 
I've removed the adapter completly and installed new, same result.
There is a new `input_text, but this is`not writable and always shows `(null)`
The log shows, that the input command is marked with Ack=false. 
`2022-05-29 12:11:47.708 - info: musiccast.0 (17057) state musiccast.0.YAS-306_00A0DED8DC1E.main.input changed: tv (ack = false)`
Complete debug-log and configuration here:
[musiccast.log.txt](https://github.com/foxthefox/ioBroker.musiccast/files/8793118/musiccast.log.txt)
[json.txt](https://github.com/foxthefox/ioBroker.musiccast/files/8793124/json.txt)

Edit: I've gone back some versions, seems v0.2.2 (2022-01-02) is the last with working input change. Pre1.0.0 from feb07 not working.
Edit2: FYI: I've changed input setting to old (before refactoring) logic, and this works for me: see: [https://github.com/MichaelDvP/ioBroker.musiccast/commit/c5cbde2295f0c053735c7572f751bc46c9edfcae](https://github.com/MichaelDvP/ioBroker.musiccast/commit/c5cbde2295f0c053735c7572f751bc46c9edfcae)

**Comment by MichaelDvP** [comment]
Thanks, i've changed the line 24 and confirm that this works with YAS-306 and WX-010.

**Comment by foxthefox** [comment]
thanks for testing
