### ISSUE TITLE
Wrong type of musiccast.0.WX-030_00BD7B73.main.power: "string". Please fix, while deprecated and will not work in next versions.

### ISSUE THREAD

**Issue by fischmir** [foxthefox/ioBroker.musiccast#22]
Hallo,

ich setze gerade neu auf und erhalte folgenden Meldung:

Wrong type of musiccast.0.WX-030_00BD7B73.main.power: "string". Please fix, while deprecated and will not work in next versions.

Ich weiß nicht genau, was zu tun ist. Kann ich mit noch mehr Infos dienen?

**Comment by foxthefox** [comment]
ich denke das kommt vom javascript adapater.
werde wohl mal standby/on in 0/1 verwandeln müssen

**Comment by Andygoblok** [comment]
Ich hatte auch das Problem, konnte es aber in ioBroker lösen. Indem ich unter Objects/musiccast/?device?/main/power von value auf string geändert habe und dann in scripts mit "on" und "standby" arbeite.

**Comment by Scrounger** [comment]
@foxthefox 
Das muss auch ein String sein, da die Api den Befehl 'on' bzw. 'standby' erwartet.
Dadurch das das jetzt ein boolean Wert ist wird in die Api 'true' bzw. 'false' geschickt, womit die Box natürlich nix anfangen kann.

Wenn boolean, dann muss hier eine Übersetzung des Adapters in "on" bzw "standby" erfolgen.
Grundsätzlich bitte an die type definition halten, boolean kann nur die Werte 'true' und 'false' annehmen.

Das leider bei deinem anderen [Adapter Fritzdect ](https://github.com/foxthefox/ioBroker.fritzdect/issues/26) ebefalls ein Problem.

**Comment by Scrounger** [comment]
fixed in #25

**Comment by foxthefox** [comment]
Danke
