### ISSUE TITLE
Datenpunkt "link_audio_delay" ändert nichts

### ISSUE THREAD

**Issue by frank2604** [foxthefox/ioBroker.musiccast#29]
Hallo Klaus,

der DP link_audio_delay kann zwar editiert werden, führt aber zu keiner Veränderung in MC, obwohl er als schreibender Datenpunkt ausgelegt ist. Wenn ich in der App umstelle, wird der Datenpunkt angepasst, aber umgekehrt eben nicht.

Kannst Du das einmal überprüfen?

Für mich ist das essentiell, da mal Musik, mal Videoinhalte vom Master "Wohnzimmer" gespielt werden und ich die Audio-Verzögerung zwischen "audio_sync" und "lip_sync" umschalten muss.

Vielen Dank vorab.

Frank

PS: Super Adapter!

**Comment by foxthefox** [comment]
Hallo Frank,

ja der Punkt ist schreibbar, aber ich werte es derzeitig noch nicht aus. Da muß ich etwas im code ergänzen.

Gruß
Klaus

**Comment by foxthefox** [comment]
evtl. kannst du die Version 0.1.3 aus github mal testen.

**Comment by foxthefox** [comment]
Im Forum erfolgreich getestet gemeldet
