### ISSUE TITLE
Please check package.json

### ISSUE THREAD

**Issue by mcm1957** [foxthefox/ioBroker.musiccast#295]
Package.json seems to contain TWO entries for axios.
https://github.com/foxthefox/ioBroker.musiccast/blob/3e54d584927a21bca73141dac335a4f50ce583c1/package.json#L32

**Comment by mcm1957** [comment]
Ok, I NEVER had to manually merge dependabot PRs.

Simply add a comment '@dependabot recreate' and dependabot will recreate the PR and this should be without any merge conflicts

**Comment by foxthefox** [comment]
Thanks
