### ISSUE TITLE
Keine Aktualisierung

### ISSUE THREAD

**Issue by sigi2345** [foxthefox/ioBroker.musiccast#32]
Hallo, der Adapter aktualisiert nicht mehr.
Nur nach einen Neustart werden die DP aktualisiert.

`[{},{"device":"RX-V481_08125F03","request":"/system/getDeviceInfo","responses":{"response_code":0,"model_name":"RX-V481","destination":"BG","device_id":"00A0DEFA01A7","system_id":"08125F03","system_version":2.65,"api_version":2.04,"netmodule_generation":1,"netmodule_version":"1813 ","netmodule_checksum":"4E2DC16D","operation_mode":"normal","update_error_code":"00000000"}},{"device":"RX-V481_08125F03","request":"/system/getFeatures","responses":{"response_code":0,"system":{"func_list":["wired_lan","wireless_lan","wireless_direct","network_standby","network_standby_auto","bluetooth_standby","bluetooth_tx_setting","zone_b_volume_sync","hdmi_out_1","airplay","disklavier_settings","network_reboot"],"zone_num":2,"input_list":[{"id":"spotify","distribution_enable":true,"rename_enable":false,"account_enable":false,"play_info_type":"netusb"},{"id":"juke","distribution_enable":true,"rename_enable":false,"account_enable":true,"play_info_type":"netusb"},{"id":"qobuz","distribution_enable":true,"rename_enable":false,"account_enable":true,"play_info_type":"netusb"},{"id":"airplay","distribution_enable":false,"rename_enable":false,"account_enable":false,"play_info_type":"netusb"},{"id":"mc_link","distribution_enable":false,"rename_enable":true,"account_enable":false,"play_info_type":"netusb"},{"id":"server","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"netusb"},{"id":"net_radio","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"netusb"},{"id":"bluetooth","distribution_enable":true,"rename_enable":false,"account_enable":false,"play_info_type":"netusb"},{"id":"usb","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"netusb"},{"id":"tuner","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"tuner"},{"id":"hdmi1","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"none"},{"id":"hdmi2","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"none"},{"id":"hdmi3","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"none"},{"id":"hdmi4","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"none"},{"id":"av1","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"none"},{"id":"av2","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"none"},{"id":"av3","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"none"},{"id":"av4","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"none"},{"id":"audio1","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"none"},{"id":"audio2","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"none"},{"id":"aux","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"none"}]},"zone":[{"id":"main","func_list":["power","sleep","volume","mute","sound_program","direct","enhancer","tone_control","dialogue_level","signal_info","prepare_input_change","link_control","link_audio_delay","link_audio_quality","scene","cursor","menu","surr_decoder_type","contents_display","actual_volume"],"input_list":["spotify","juke","qobuz","airplay","mc_link","server","net_radio","bluetooth","usb","tuner","hdmi1","hdmi2","hdmi3","hdmi4","av1","av2","av3","av4","audio1","audio2","aux"],"sound_program_list":["munich","vienna","chamber","cellar_club","roxy_theatre","bottom_line","sports","action_game","roleplaying_game","music_video","standard","spectacle","sci-fi","adventure","drama","mono_movie","2ch_stereo","5ch_stereo","surr_decoder","straight"],"surr_decoder_type_list":["toggle","dolby_pl","dolby_pl2x_movie","dolby_pl2x_music","dolby_pl2x_game","dts_neo6_cinema","dts_neo6_music"],"tone_control_mode_list":["manual"],"link_control_list":["speed","standard","stability"],"link_audio_delay_list":["audio_sync","lip_sync"],"link_audio_quality_list":["compressed","uncompressed"],"range_step":[{"id":"volume","min":0,"max":161,"step":1},{"id":"tone_control","min":-12,"max":12,"step":1},{"id":"dialogue_level","min":0,"max":3,"step":1},{"id":"actual_volume_db","min":-80.5,"max":16.5,"step":0.5},{"id":"actual_volume_numeric","min":0,"max":97,"step":0.5}],"scene_num":4,"cursor_list":["up","down","left","right","select","return"],"menu_list":["on_screen","top_menu","menu","option","display"],"actual_volume_mode_list":["db","numeric"]},{"id":"zone2","zone_b":true,"func_list":["power","volume","mute","prepare_input_change","actual_volume"],"input_list":["spotify","juke","qobuz","airplay","mc_link","server","net_radio","bluetooth","usb","tuner","hdmi1","hdmi2","hdmi3","hdmi4","av1","av2","av3","av4","audio1","audio2","aux"],"range_step":[{"id":"volume","min":0,"max":161,"step":1},{"id":"actual_volume_db","min":-80.5,"max":16.5,"step":0.5},{"id":"actual_volume_numeric","min":0,"max":97,"step":0.5}],"actual_volume_mode_list":["db","numeric"]}],"tuner":{"func_list":["am","fm","rds"],"range_step":[{"id":"am","min":531,"max":1611,"step":9},{"id":"fm","min":87500,"max":108000,"step":50}],"preset":{"type":"common","num":40}},"netusb":{"func_list":["recent_info","play_queue","mc_playlist","streaming_service_use"],"preset":{"num":40},"recent_info":{"num":40},"play_queue":{"size":200},"mc_playlist":{"size":200,"num":5},"net_radio_type":"airable","pandora":{"sort_option_list":["date","alphabet"]}},"distribution":{"version":2,"compatible_client":[2],"client_max":9,"server_zone_list":["main"]},"ccs":{"supported":true},"privacy":{"gdpr_supported":true}}},{"device":"RX-V481_08125F03","request":"/main/getStatus","responses":{"response_code":0,"power":"on","sleep":0,"volume":49,"mute":false,"max_volume":161,"input":"net_radio","distribution_enable":true,"sound_program":"2ch_stereo","surr_decoder_type":"dolby_pl","direct":false,"enhancer":true,"tone_control":{"mode":"manual","bass":12,"treble":2},"dialogue_level":3,"link_control":"standard","link_audio_delay":"lip_sync","link_audio_quality":"compressed","disable_flags":0,"actual_volume":{"mode":"db","value":-56,"unit":"dB"},"contents_display":true}},{"device":"RX-V481","request":"/netusb/getPlayInfo","responses":{"response_code":0,"input":"net_radio","play_queue_type":"system","playback":"play","repeat":"off","shuffle":"off","play_time":177,"total_time":0,"artist":"Hitradio Ö3 (Vienna/German)","album":"","track":"Avec - Home","albumart_url":"/YamahaRemoteControl/AlbumART/AlbumART6460.png","albumart_id":6460,"usb_devicetype":"unknown","auto_stopped":false,"attribute":16785411,"repeat_available":[],"shuffle_available":[]}}]

`

Adapter : 
V 0.1.3

System:

Platform: Windows
os: win32
Architecture: x64
RAM: 7.9 GB 
Node.js: v10.16.3
NPM: 6.9.0
JS: 2.2.8
Admin: 3.7.9

**Comment by foxthefox** [comment]
wird gar nichts mehr aktualisiert, oder bezieht sich dies auf die Aktualisierung von AlbumArt?
dies hier:
https://forum.iobroker.net/topic/29580/musiccast-bilder-werden-nicht-angezeigt/3
zur Eingrenzung wär es recht hilreich

**Comment by sigi2345** [comment]
Es wird gar nichts mehr aktualisiert, nur nach Neustart.
In der Handy App geht es, aber reagiert langsam.

**Comment by foxthefox** [comment]
Was heißt Handy App? Die Musiccast App von Yamaha?

**Comment by sigi2345** [comment]
> Die Musiccast App von Yamaha?

Ja

**Comment by foxthefox** [comment]
Ist denn alles mit dem Netzwerk in Ordnung, wenn die Musiccast App langsam reagiert, dürfte es dem Adapter nicht besser gehen

**Comment by sigi2345** [comment]
Erledigt.
