### ISSUE TITLE
Update stable version in repo to 0.1.3

### ISSUE THREAD

**Issue by GermanBluefox** [foxthefox/ioBroker.musiccast#35]
# Think about update stable version to 0.1.3
**Version**: stable=**0.0.8** (639 days old) => latest=**0.1.3** (28 days old)
**Installs**: stable=**248** (52.43%), latest=**105** (22.2%), total=**473**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L835)

**Comment by foxthefox** [comment]
done with
ioBroker/ioBroker.repositories#659
