### ISSUE TITLE
Warnings in IOBroker like *main.surround_ai" has no existing object, this might lead to an error in future versions

### ISSUE THREAD

**Issue by derrapf** [foxthefox/ioBroker.musiccast#366]
I get several warnings in the logfile of IOBroker

State "musiccast.0.RX-A3080_00E9F513.main.surround_ai" has no existing object, this might lead to an error in future versions
and constantly

State value to set for "musiccast.0.RX-A3080_00E9F513.tuner.dab.freq" has value "0" less than min "174000"
State value to set for "musiccast.0.RX-A3080_00E9F513.tuner.dab.bit_rate" has value "0" less than min "32"

</body>
</html>
How can I get rid of those?

**Screenshots & Logfiles**  
[musiccast.json](https://github.com/user-attachments/files/16615122/musiccast.json)

**Versions:**  
 - Adapter version: v1.1.3
 - JS-Controller version: 5.0.19
 - Node version: v20.16.0
 - Operating system: Debian GNU/Linux  under ProxMox

**Comment by foxthefox** [comment]
Please install version 1.1.4 from git or npm, then it is gone

**Comment by foxthefox** [comment]
1.1.4 is now in stable
