### ISSUE TITLE
Please formulate your CSS instructions more specifically

### ISSUE THREAD

**Issue by oweitman** [foxthefox/ioBroker.musiccast#45]
Please formulate your CSS instructions more specifically and limit the effectiveness with your own container.
Your generally defined CSS classes (e.g. div.row) have negative side effects even if the CSS classes were defined more specifically in the other area (iobroker.tvprogram).

https://github.com/foxthefox/ioBroker.musiccast/blob/c3a7c14cdc2aa21c3e5d3b7dd693d8e84a0044a3/widgets/musiccast/css/style.css#L12

**Comment by foxthefox** [comment]
I would be happy, if you create a PR for this, I am struggling with the damn widgets at all.

**Comment by oweitman** [comment]
closed. no plan for improvement!
