### ISSUE TITLE
Can't set *.max_volume - ist it possible to make it write able?

### ISSUE THREAD

**Issue by manoloxxl** [foxthefox/ioBroker.musiccast#56]
**Describe the bug**  
main.max.volume and zone2.max.volume are only read only in iobroker object list

**Expected behavior**  
It woul be great, if i can write them also to set the max - volume

**Versions:**  
 - Adapter version: 0.1.5
 - JS-Controller version: 3.2.16
 - Node version: v12.21.0
 - Operating system: Docker
 - Reveiver: RX-V683

**Comment by foxthefox** [comment]
the max volume is predefined by the receiver. The API does not have a possibility to send the max volume.
So what should I the do with the written max volume?

**Comment by manoloxxl** [comment]
> the max volume is predefined by the receiver. The API does not have a possibility to send the max volume.
> So what should I the do with the written max volume?

In the RX-V683 this is an system option in the settings that can be set by the remote controll in the receiver setup. For Main and Zone2.

Also i'm able to change the setting with the node-red yamaha adapter ().
When i inject a new value (-50 or 50 or 100 - the values there are in dB) i can see, that the value in the iobroker is chaning. It's not showing dB Values, but tha value is chaning after the inject in node-red

-10.0 dB in receiver and node-red is "141" in your adapter
+10.0dB in receiver and node-red is "161" in your adapter


![Greenshot 2021-04-02 09 44 15](https://user-images.githubusercontent.com/25949606/113394216-1f0a1a80-9398-11eb-8506-e9ba8fa1896d.png)

**Comment by foxthefox** [comment]
the node-red is using another API, not the yxc-musiccast one. I think there is another adapter in iobroker available, which is using the other API.

The adapter takes over the given values from the API and does not try to calculate on an unknown basis. So the difference between one and another is related to the provided information through the API.

**Comment by foxthefox** [comment]
Maybe there is a command in the YXC-API available, but then I do not have an information how to implement it

**Comment by manoloxxl** [comment]
Oh, okay. Thanks! I will have a look into the other adapter.
