### ISSUE TITLE
Keine Verbindung mehr mit Geräten nach Firmware Update von 2.15 -> 2.16 (ISX und WX 010)

### ISSUE THREAD

**Issue by mootec** [foxthefox/ioBroker.musiccast#98]
Keine Verbindung mehr mit Geräten der Firmware 2.16 (siehe Log).
Ein Gerät habe ich nicht geupdatet, da funktioniert noch alles.

(Installiert ist der Adapter in der aktuellen Version: 0.2.0 (1~))

![image](https://user-images.githubusercontent.com/7147746/134641599-70aaf0c3-e8c0-4791-ba06-9bc96a86dc5a.png)

**Comment by foxthefox** [comment]
da scheint etwas grundsätzlich anders geworden zu sein, daß muß ich nachforschen, sofern es denn geht

**Comment by mootec** [comment]
Ich habe nur die offiziellen Firmware Änderungen auf der japanischen Yamaha Webseite gefunden. Die sind auch nicht sehr aussagekräftig, aber im Gegensatz zur deutschen Seite wenigstens etwas.
https://jp.yamaha.com/support/updates/wx010.html

Da steht folgendes auf deutsch (ich hoffe man kann es lesen):
![image](https://user-images.githubusercontent.com/7147746/134645325-de5d3c0e-4520-4096-9eba-f65bdbee31b9.png)

**Comment by foxthefox** [comment]
danke, viel ideen gibt es einem nicht.

**Comment by foxthefox** [comment]
was mich noch etwas stutzig macht, ist der port 80. Ist der so parametriert unter IP Adresse??

**Comment by mootec** [comment]
Ne, ich habe da nur die IP Adresse drin:
![image](https://user-images.githubusercontent.com/7147746/134667309-e8fb48eb-d71f-44e0-b935-d91a36798a03.png)

**Comment by mootec** [comment]
Im Browser ist der Link für z.b. getMusicZoneInfo ohne Probleme aufrufbar:
http://(ip)/YamahaExtendedControl/v1/main/getStatus

**Comment by foxthefox** [comment]
OK, alles klar

**Comment by mootec** [comment]
Hat sich von selbst erledigt. Geändert habe ich in dem Kontext nichts. Ich hatte die Geräte eine Weile nun aus der Konfiguration entfernt, um keine Fehlermeldungen zu haben und heute wieder hinzugefügt: funktioniert wieder.
